services:
  backend:
    build: .
    container_name: drugstore-backend
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:16
    container_name: drugstore-db
    restart: always
    environment:
      POSTGRES_DB: drugstore
      POSTGRES_USER: druguser
      POSTGRES_PASSWORD: drugpass
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    container_name: drugstore-pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@drugstore.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db

  # service para executar a suíte de testes do projeto
  tests:
    build: .
    container_name: drugstore-tests
    # monta o código para que testes e arquivos gerados (ex: test.db) fiquem disponíveis
    volumes:
      - .:/app
    # garante que as variáveis de ambiente do projeto sejam carregadas, mas sobrescreve DATABASE_URL
    env_file:
      - .env
    environment:
      # força uso de sqlite local para execuções de teste isoladas
      DATABASE_URL: sqlite:///./test.db
      # garante que o pacote 'app' seja importável dentro do container
      PYTHONPATH: /app
    working_dir: /app
    depends_on:
      - db
    # comando que roda os testes
    command: ["pytest", "-q","-vvvv"]

volumes:
  postgres_data:
